name: store_demo
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  http: ^0.13.5
  flutter_secure_storage: ^6.0.0
  google_fonts: ^3.0.1
  flutter_paystack:
    git:
      url: https://github.com/definitelyme/flutter_paystack.git
      ref: a4a33c3dd0a12f46d655a2e63d11e9f20ba82d01
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
 

  fonts:
    - family: BrandonGrotesque
      fonts:
        - asset: assets/fonts/Brandon_bld.otf
        - asset: assets/fonts/Brandon_light.otf
        - asset: assets/fonts/Brandon_med.otf
        - asset: assets/fonts/Brandon_reg.otf
        - asset: assets/fonts/Brandon_thin.otf
        - asset: assets/fonts/brandon-grotesque-black-58a8a3e824392.otf
        - asset: assets/fonts/brandon-grotesque-light-58a8a4b38001d.otf
        

        